[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "adventofcode"
path = "./src/2024/main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }