/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
    kotlin("jvm") version "1.9.20"
    application
}

sourceSets.main {
    java.srcDirs(".")
}

repositories {
    mavenCentral() 
}

dependencies {
    // Used to launch several aoc days concurrently
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    // testImplementation(kotlin("test"))
    // testImplementation(kotlin("test-junit"))
}

application {
    mainClass.set("aoc2023.MainKt")
}

// kotlin {
//     // jvm {
//     //     testRuns["test"].executionTask.configure {
//     //         useJUnitPlatform()
//     //     }
//     // }
//     sourceSets {
//         val main by getting {
//             dependencies {
//                 implementation(kotlin("test"))
//             }
//         }
//     }
// }

// tasks.test {
//     useJUnitPlatform()
// }

tasks.withType<Jar> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    // Otherwise you'll get a "No main manifest attribute" error
    manifest {
        attributes["Main-Class"] = "aoc2023.MainKt"
    }

    // To add all of the dependencies otherwise a "NoClassDefFoundError" error
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}
