/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
    kotlin("jvm") version "1.9.20"
    application
}

sourceSets.main {
    java.srcDirs(".")
}

repositories {
    mavenCentral() 
}

application {
    mainClass.set("aoc2023.MainKt")
}